import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { supabase } from "../../../../lib/supabase";
import { getRoomTrivia, getTriviaPlayerState, getTriviaTimeline, joinTriviaRound, submitTriviaAnswer, type TriviaPlayerState } from "../../../../lib/lightningTrivia";
import { createGuestSession, readStoredGuestSession } from "../../../lib/matchmaking";

const faction: Record<string, { emoji: string; label: string }> = { pack: { emoji: "🐺", label: "PACK" }, marsh: { emoji: "🐸", label: "MARSH" }, pride: { emoji: "🦁", label: "PRIDE" } };

export default function LightningTriviaScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const roomId = String(id);
  const [state, setState] = useState<TriviaPlayerState | null>(null);
  const [now, setNow] = useState(Date.now());
  const [selected, setSelected] = useState<Record<number, number>>({});
  const [feedback, setFeedback] = useState<Record<number, { correct: boolean; score: number }>>({});
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [guestToken, setGuestToken] = useState<string | null>(null);
  const load = useCallback(async () => {
    const round = await getRoomTrivia(supabase, roomId);
    if (!round) throw new Error("No Lightning Trivia round is available.");
    const { data: authData } = await supabase.auth.getUser();
    let token = guestToken ?? (await readStoredGuestSession())?.guestToken ?? null;
    if (!authData.user && !token) { token = (await createGuestSession()).guestToken; setGuestToken(token); }
    const next = await getTriviaPlayerState(supabase, round.id, token);
    setState(next); setSelected(Object.fromEntries(next.answers.map((answer) => [answer.question_order, answer.selected_answer]))); setFeedback(Object.fromEntries(next.answers.map((answer) => [answer.question_order, { correct: answer.is_correct, score: answer.score_awarded }])));
  }, [guestToken, roomId]);
  useEffect(() => {
    void load().catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load trivia."));
    const clock = setInterval(() => setNow(Date.now()), 50); const poll = setInterval(() => void load(), 2000);
    const channel = supabase.channel(`mobile-trivia-${roomId}`).on("postgres_changes", { event: "*", schema: "public", table: "trivia_rounds", filter: `room_id=eq.${roomId}` }, () => void load()).subscribe();
    return () => { clearInterval(clock); clearInterval(poll); void supabase.removeChannel(channel); };
  }, [load, roomId]);
  const timeline = useMemo(() => state ? getTriviaTimeline(state.round.starts_at, state.round.seconds_per_question, state.round.feedback_ms, now) : null, [now, state]);
  const question = timeline && timeline.questionIndex >= 0 && timeline.questionIndex < 10 ? state?.questions[timeline.questionIndex] : null;
  const locked = question ? selected[question.question_order] : undefined;
  async function join() { if (!state || busy) return; setBusy(true); try { await joinTriviaRound(supabase, state.round.id, guestToken); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not join."); } finally { setBusy(false); } }
  async function answer(index: number) { if (!state || !question || locked !== undefined || timeline?.phase !== "question") return; setSelected((current) => ({ ...current, [question.question_order]: index })); try { const result = await submitTriviaAnswer(supabase, state.round.id, question.question_order, index, guestToken); setFeedback((current) => ({ ...current, [question.question_order]: { correct: result.correct, score: result.score_awarded } })); } catch { /* The immediate lock remains; timeout resolves as TIME. */ } }

  if (!state) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator color="#FACC15" size="large" /><Text style={styles.message}>{error || "LOADING ROUND…"}</Text></View></SafeAreaView>;
  if (state.round.status === "ended") return <SafeAreaView style={styles.safe}><View style={styles.results}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>← ROOM</Text></TouchableOpacity><Text style={styles.eyebrow}>ROUND COMPLETE</Text><Text style={styles.heading}>FACTION RESULTS</Text>{(state.round.standings ?? []).map((standing) => <View key={standing.faction_key} style={styles.resultRow}><Text style={styles.resultName}>{standing.eligible ? `${standing.placement}. ` : ""}{faction[standing.faction_key]?.emoji} {faction[standing.faction_key]?.label ?? standing.faction_key.toUpperCase()}</Text><Text style={styles.resultScore}>{standing.eligible ? standing.average_score.toLocaleString() : "INSUFFICIENT"}</Text></View>)}{state.player_result ? <View style={styles.myScore}><Text style={styles.eyebrow}>YOUR SCORE</Text><Text style={styles.score}>{state.player_result.total_score.toLocaleString()}</Text><Text style={styles.sub}>{state.player_result.correct_count}/10 correct</Text>{state.faction_key ? <Text style={styles.counted}>{state.player_result.counted_for_faction ? `YOUR SCORE COUNTED FOR ${faction[state.faction_key]?.label ?? state.faction_key}` : `You helped ${faction[state.faction_key]?.label ?? state.faction_key} compete.`}</Text> : null}</View> : null}</View></SafeAreaView>;
  const countdown = Math.max(0, Math.ceil((Date.parse(state.round.starts_at) - now) / 1000));
  if (!state.joined) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.bolt}>⚡</Text><Text style={styles.eyebrow}>LIGHTNING TRIVIA</Text><Text style={styles.heading}>10 QUESTIONS.{"\n"}5 SECONDS EACH.</Text>{state.round.status === "scheduled" && countdown > 0 ? <><Text style={styles.countdown}>{countdown}</Text><TouchableOpacity disabled={busy} onPress={() => void join()} style={styles.join}><Text style={styles.joinText}>{busy ? "JOINING…" : "JOIN ROUND"}</Text></TouchableOpacity></> : <Text style={styles.message}>Round in progress.{"\n"}Joining closed at the start.</Text>}{error ? <Text style={styles.error}>{error}</Text> : null}</View></SafeAreaView>;
  if (timeline?.phase === "countdown") return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.eyebrow}>ROUND STARTS IN</Text><Text style={styles.giant}>{Math.max(1, Math.ceil(timeline.countdownMs / 1000))}</Text></View></SafeAreaView>;
  if (timeline?.phase === "complete" || state.round.status === "scoring") return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.bolt}>⚡</Text><Text style={styles.heading}>CALCULATING{"\n"}THE BATTLE…</Text></View></SafeAreaView>;
  if (!timeline || !question) return null;
  const result = feedback[question.question_order];
  if (timeline?.phase === "feedback") return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={[styles.feedback, result?.correct ? styles.correct : styles.wrong]}>{result ? result.correct ? "CORRECT" : "WRONG" : "TIME"}</Text>{result?.correct ? <Text style={styles.bonus}>+{result.score}</Text> : null}</View></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.game}><View style={styles.top}><Text style={styles.questionNumber}>QUESTION {question.question_order} / 10</Text><View style={[styles.timer, timeline.remainingMs < 1500 && styles.timerDanger]}><Text style={styles.timerText}>{Math.max(1, Math.ceil(timeline.remainingMs / 1000))}</Text></View></View><Text style={styles.question}>{question.question_text}</Text><View style={styles.answers}>{question.answers.map((choice, index) => <TouchableOpacity key={index} disabled={locked !== undefined} onPress={() => void answer(index)} style={[styles.answer, locked === index && styles.answerSelected, locked !== undefined && locked !== index && styles.answerDim]}><Text style={[styles.answerText, locked === index && styles.answerTextSelected]}>{String.fromCharCode(65 + index)}  {choice}</Text></TouchableOpacity>)}</View></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#07000F" }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 }, game: { flex: 1, padding: 18 }, results: { flex: 1, padding: 20 }, back: { color: "#D8B4FE", fontWeight: "900", marginBottom: 28 }, bolt: { fontSize: 64, marginBottom: 16 }, eyebrow: { color: "#FDE047", fontSize: 13, fontWeight: "900", letterSpacing: 2, textAlign: "center" }, heading: { color: "#FFF", fontSize: 35, fontWeight: "900", textAlign: "center", marginTop: 12 }, message: { color: "#D4D4D8", fontSize: 17, fontWeight: "700", textAlign: "center", marginTop: 20 }, error: { color: "#FCA5A5", marginTop: 16, fontWeight: "700", textAlign: "center" }, countdown: { color: "#FFF", fontSize: 72, fontWeight: "900", marginTop: 28 }, giant: { color: "#FFF", fontSize: 150, fontWeight: "900" }, join: { backgroundColor: "#FACC15", width: "100%", minHeight: 58, borderRadius: 14, alignItems: "center", justifyContent: "center", marginTop: 22 }, joinText: { color: "#09090B", fontSize: 20, fontWeight: "900" }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, questionNumber: { color: "#D4D4D8", fontWeight: "900" }, timer: { width: 64, height: 64, borderRadius: 32, borderWidth: 4, borderColor: "#FDE047", alignItems: "center", justifyContent: "center" }, timerDanger: { borderColor: "#F87171" }, timerText: { color: "#FFF", fontSize: 24, fontWeight: "900" }, question: { color: "#FFF", fontSize: 30, lineHeight: 37, fontWeight: "900", minHeight: 145, textAlignVertical: "center" }, answers: { flex: 1, gap: 10 }, answer: { flex: 1, maxHeight: 112, minHeight: 66, justifyContent: "center", borderRadius: 14, borderWidth: 1, borderColor: "rgba(216,180,254,.35)", backgroundColor: "rgba(126,34,206,.2)", paddingHorizontal: 18 }, answerSelected: { backgroundColor: "#FACC15", borderColor: "#FEF08A" }, answerDim: { opacity: .35 }, answerText: { color: "#FFF", fontSize: 20, fontWeight: "900" }, answerTextSelected: { color: "#09090B" }, feedback: { fontSize: 58, fontWeight: "900" }, correct: { color: "#6EE7B7" }, wrong: { color: "#FCA5A5" }, bonus: { color: "#FDE047", fontSize: 40, fontWeight: "900", marginTop: 12 }, resultRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, borderRadius: 13, backgroundColor: "rgba(255,255,255,.06)", marginTop: 10 }, resultName: { color: "#FFF", fontSize: 18, fontWeight: "900", flex: 1 }, resultScore: { color: "#FFF", fontWeight: "900" }, myScore: { marginTop: 24, padding: 20, borderRadius: 16, backgroundColor: "rgba(250,204,21,.12)", borderWidth: 1, borderColor: "rgba(250,204,21,.35)", alignItems: "center" }, score: { color: "#FFF", fontSize: 52, fontWeight: "900", marginTop: 6 }, sub: { color: "#D4D4D8", fontWeight: "700" }, counted: { color: "#FDE047", fontWeight: "900", marginTop: 14, textAlign: "center" } });
