import { Image } from "expo-image";
import * as ImagePicker from "expo-image-picker";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { getEventSeriesProfile } from "../../../../lib/eventSeries";
import { supabase } from "../../../../lib/supabase";

export default function EditSeriesScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [coverUrl, setCoverUrl] = useState<string | null>(null); const [coverUri, setCoverUri] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!id) return; getEventSeriesProfile(id).then((series) => { if (!series?.is_owner) throw new Error("Only the series host can edit it."); setName(series.name); setDescription(series.description || ""); setCoverUrl(series.cover_image_url); }).catch((error) => Alert.alert("Series unavailable", error instanceof Error ? error.message : "Please try again.")); }, [id]);
  async function pickCover() { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: true, aspect: [16, 9], quality: 0.85 }); if (!result.canceled) setCoverUri(result.assets[0].uri); }
  async function save() { if (!id || !name.trim() || saving) return; setSaving(true); try { let nextCover = coverUrl; if (coverUri) { const { data: userData } = await supabase.auth.getUser(); if (!userData.user) throw new Error("Sign in to edit this series."); const extension = coverUri.split(".").pop()?.split("?")[0] || "jpg"; const bytes = await (await fetch(coverUri)).arrayBuffer(); const path = `${userData.user.id}/series-${Date.now()}.${extension}`; const { error: uploadError } = await supabase.storage.from("event-images").upload(path, bytes, { contentType: `image/${extension === "png" ? "png" : "jpeg"}` }); if (uploadError) throw uploadError; nextCover = supabase.storage.from("event-images").getPublicUrl(path).data.publicUrl; } const { error } = await supabase.rpc("update_event_series", { p_series_id: id, p_name: name.trim(), p_description: description.trim() || null, p_cover_image_url: nextCover }); if (error) throw error; router.replace(`/series/${id}` as never); } catch (error) { Alert.alert("Could not update series", error instanceof Error ? error.message : "Please try again."); setSaving(false); } }
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>Back to series</Text></TouchableOpacity><Text style={styles.title}>Edit Event Series</Text><Text style={styles.label}>Series name</Text><TextInput value={name} onChangeText={setName} maxLength={100} style={styles.input} /><Text style={styles.label}>Description</Text><TextInput value={description} onChangeText={setDescription} maxLength={1000} multiline style={[styles.input, styles.textarea]} /><Text style={styles.label}>Cover image</Text><TouchableOpacity style={styles.coverButton} onPress={pickCover}>{coverUri || coverUrl ? <Image source={{ uri: coverUri || coverUrl || "" }} style={styles.cover} contentFit="cover" /> : <View style={styles.coverEmpty}><Text style={styles.coverText}>Add cover image</Text></View>}</TouchableOpacity><TouchableOpacity style={[styles.save, (!name.trim() || saving) && styles.disabled]} disabled={!name.trim() || saving} onPress={save}><Text style={styles.saveText}>{saving ? "Saving..." : "Save changes"}</Text></TouchableOpacity></ScrollView>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: "#05040B" }, content: { padding: 24, paddingTop: 56, paddingBottom: 60 }, back: { color: "#C9A6FF", fontWeight: "800" }, title: { color: "#FFF", fontSize: 36, fontWeight: "900", marginTop: 34, marginBottom: 18 }, label: { color: "#FFF", fontSize: 14, fontWeight: "900", marginBottom: 8, marginTop: 18 }, input: { minHeight: 50, backgroundColor: "#111019", borderColor: "#2B2632", borderWidth: 1, borderRadius: 8, color: "#FFF", paddingHorizontal: 14 }, textarea: { height: 130, paddingTop: 14, textAlignVertical: "top" }, coverButton: { height: 170, borderRadius: 8, overflow: "hidden" }, cover: { width: "100%", height: "100%" }, coverEmpty: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: "#17131E" }, coverText: { color: "#C9A6FF", fontWeight: "900" }, save: { alignItems: "center", backgroundColor: "#8B3DFF", borderRadius: 8, marginTop: 30, paddingVertical: 16 }, disabled: { opacity: 0.5 }, saveText: { color: "#FFF", fontWeight: "900", fontSize: 16 } });
